### ISSUE TITLE
Summation Items

### ISSUE THREAD

**Issue by DarkArc** [Skelril/Skree#32]
- [x] Hymn of Summation
- [x] Scroll of Summation

**Comment by DarkArc** [comment]
I'm not sure if these should actually be brought back as charms, rather than items.

**Comment by DarkArc** [comment]
@Skelril/mc-management

**Comment by Cow-Fu** [comment]
I think a charm would be fine for the Hymn of Summation, but how would it work with the Scroll of Summation since it's consumable? Personally, I'm fine with the Hymn being a charm since it's fairly rare and the Scroll being an item because it's much more common.

**Comment by DarkArc** [comment]
Hm, you bring up a good point. There are definitely issues with the scroll being consumable. It may also be confusing in that we have "scrolls" now to create charms.

What if we make two items, a hymn, and a tablet? Tablets take "action charms" and are consumed upon use. Hymns take the same "action charms" but degrade rather than being consumed, you can get different base hymns, and add paper to repair them before they break -- similar to the Red Feather plans. That way we have something very similar to our other systems, in that things can be tiered -- except in this case tiered in terms of durability rather than power.
